import google.generativeai as genai
from app.core.config import settings
from app.infrastructure.ai_provider import AIProvider
from app.core.logging import logger

class GeminiClient(AIProvider):
    """
    Google Gemini AI implementation of the AIProvider interface.
    """
    def __init__(self):
        if not settings.GEMINI_API_KEY:
            logger.warning("GEMINI_API_KEY is not set in environment settings.")
        
        genai.configure(api_key=settings.GEMINI_API_KEY)
        self.model = genai.GenerativeModel('gemini-pro')

    async def generate_response(self, prompt: str) -> str:
        """
        Generates a response using Google Gemini AI.
        """
        try:
            # Note: The official SDK is blocking, in a production app 
            # you might want to run this in a threadpool if not using async version.
            # For simplicity and following the 'real working logic' requirement:
            response = self.model.generate_content(prompt)
            if response and response.text:
                return response.text
            return "No response generated by AI."
        except Exception as e:
            logger.error(f"Error generating response from Gemini: {str(e)}")
            raise Exception(f"AI Provider Error: {str(e)}")
