import asyncio
from typing import Any, List, Optional, Type, Union

import vertexai
from google import genai
from pydantic import BaseModel
from vertexai.language_models import TextEmbeddingModel

from app.core.config import settings
from app.core.logging import logger
from app.infrastructure.ai_provider import AIProvider


class GeminiClient(AIProvider):
    """
    Google Gemini AI implementation using the modern google-genai SDK
    fully powered by Vertex AI for text and embeddings.
    """
    def __init__(self):
        """
        Initializes the Gemini client with Vertex AI backend and pre-loads the embedding model.
        """
        try:
            # The new SDK can be initialized to use Vertex AI backend
            self.client = genai.Client(
                vertexai=True, 
                project=settings.FIRESTORE_PROJECT_ID, 
                location=settings.GCP_LOCATION
            )
            self.model_name = 'gemini-2.0-flash'
            
            # Explicitly load the embedding model via Vertex AI
            vertexai.init(project=settings.FIRESTORE_PROJECT_ID, location=settings.GCP_LOCATION)
            self.embedding_model = TextEmbeddingModel.from_pretrained("text-multilingual-embedding-002")
            logger.info("GeminiClient initialized with Vertex AI backend.")
        except Exception as e:
            logger.error(f"Failed to initialize GeminiClient with Vertex AI: {e}")
            self.embedding_model = None
            # Fallback to standard Google AI if Vertex fails initialization
            if settings.GEMINI_API_KEY:
                self.client = genai.Client(api_key=settings.GEMINI_API_KEY)
                logger.info("Falling back to Google AI (API Key) backend.")

    async def generate_response(
        self, 
        prompt: Union[str, List[Any]], 
        system_instruction: Optional[str] = None, 
        response_schema: Optional[Type[BaseModel]] = None,
        use_google_search: bool = True
    ) -> str:
        """
        Generates a text response using the configured Gemini model with optional multi-modal input and Google Search grounding.

        Args:
            prompt: The user's input (string or list of parts like text/images).
            system_instruction: Optional guidelines or persona to guide the AI's behavior.
            response_schema: Optional Pydantic model to enforce a specific JSON output structure.
            use_google_search: Whether to ground the response with real-time Google Search data.

        Returns:
            The generated text response.
        """
        try:
            from google.genai import types
            
            config_params = {
                "safety_settings": [
                    types.SafetySetting(
                        category="HARM_CATEGORY_HATE_SPEECH",
                        threshold="BLOCK_MEDIUM_AND_ABOVE",
                    ),
                    types.SafetySetting(
                        category="HARM_CATEGORY_HARASSMENT",
                        threshold="BLOCK_MEDIUM_AND_ABOVE",
                    ),
                ]
            }

            if system_instruction:
                config_params["system_instruction"] = system_instruction
            
            if response_schema:
                config_params["response_mime_type"] = "application/json"
                config_params["response_schema"] = response_schema

            # Advanced Google Service: Dynamic Retrieval (Google Search Grounding)
            if use_google_search:
                config_params["tools"] = [
                    types.Tool(google_search_retrieval=types.GoogleSearchRetrieval())
                ]
            
            config = types.GenerateContentConfig(**config_params)

            # The new SDK uses client.models.generate_content (Synchronous call wrapped in thread)
            response = await asyncio.to_thread(
                self.client.models.generate_content,
                model=self.model_name,
                contents=prompt,
                config=config
            )
            
            if response and response.text:
                return response.text
            return "No response generated by AI."
        except Exception as e:
            logger.error(f"Error generating response from Gemini: {str(e)}")
            raise Exception(f"AI Provider Error: {str(e)}") from e

    async def generate_embedding(self, text: str) -> List[float]:
        """
        Generates a vector embedding for the given text using Vertex AI.

        Args:
            text: The string to be vectorized.

        Returns:
            A list of floats representing the embedding vector.
        """
        if not self.embedding_model:
            raise Exception("Vertex AI Embedding model is not initialized.")
            
        try:
            # Synchronous call wrapped in thread
            embeddings = await asyncio.to_thread(self.embedding_model.get_embeddings, [text])
            return embeddings[0].values
        except Exception as e:
            logger.error(f"Error generating embedding from Vertex AI: {str(e)}")
            raise Exception(f"AI Provider Embedding Error: {str(e)}") from e
