from typing import Any
from google import genai
import vertexai
from vertexai.language_models import TextEmbeddingModel
from app.core.config import settings
from app.infrastructure.ai_provider import AIProvider
from app.core.logging import logger

class GeminiClient(AIProvider):
    """
    Google Gemini AI implementation using the modern google-genai SDK
    fully powered by Vertex AI for text and embeddings.
    """
    def __init__(self):
        # Initialize Vertex AI for the SDK
        try:
            # The new SDK can be initialized to use Vertex AI backend
            self.client = genai.Client(
                vertexai=True, 
                project=settings.FIRESTORE_PROJECT_ID, 
                location=settings.GCP_LOCATION
            )
            self.model_name = 'gemini-2.5-flash'
            
            # Explicitly load the embedding model via Vertex AI
            vertexai.init(project=settings.FIRESTORE_PROJECT_ID, location=settings.GCP_LOCATION)
            self.embedding_model = TextEmbeddingModel.from_pretrained("text-multilingual-embedding-002")
            logger.info("GeminiClient initialized with Vertex AI backend.")
        except Exception as e:
            logger.error(f"Failed to initialize GeminiClient with Vertex AI: {e}")
            self.embedding_model = None
            # Fallback to standard Google AI if Vertex fails initialization
            if settings.GEMINI_API_KEY:
                self.client = genai.Client(api_key=settings.GEMINI_API_KEY)
                logger.info("Falling back to Google AI (API Key) backend.")

    async def generate_response(
        self, 
        prompt: str, 
        system_instruction: str = None, 
        response_schema: Any = None
    ) -> str:
        """
        Generates a response using the latest Gemini model with optional system instructions and schema.
        """
        try:
            from google.genai import types
            
            config_params = {}
            if system_instruction:
                config_params["system_instruction"] = system_instruction
            
            if response_schema:
                config_params["response_mime_type"] = "application/json"
                config_params["response_schema"] = response_schema
            
            config = types.GenerateContentConfig(**config_params) if config_params else None

            # The new SDK uses client.models.generate_content
            response = self.client.models.generate_content(
                model=self.model_name,
                contents=prompt,
                config=config
            )
            
            if response and response.text:
                return response.text
            return "No response generated by AI."
        except Exception as e:
            logger.error(f"Error generating response from Gemini: {str(e)}")
            raise Exception(f"AI Provider Error: {str(e)}")

    async def generate_embedding(self, text: str) -> list[float]:
        """
        Generates a vector embedding for the given text using Vertex AI.
        """
        if not self.embedding_model:
            raise Exception("Vertex AI Embedding model is not initialized.")
            
        try:
            # Vertex AI SDK is blocking, but we can run it in a thread pool if needed
            # For this context, direct call is fine as it's an async service layer
            embeddings = self.embedding_model.get_embeddings([text])
            return embeddings[0].values
        except Exception as e:
            logger.error(f"Error generating embedding from Vertex AI: {str(e)}")
            raise Exception(f"AI Provider Embedding Error: {str(e)}")
